config/routes.rb
Rails.application.routes.draw do
  resources :workouts
  root 'workouts#index'
end

app/models/workout.rb
class Workout < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
before_action :find_workout, only: [:show, :edit, :update, :destroy]

  def index
    @workouts = Workout.all.order("created_at DESC")
  end

  def show
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end

  def edit
    # Captured on before_action
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def destroy
    @workout.destroy
    redirect_to root_path
  end


  private

  def workout_params
    params.require(:workout).permit(:date, :workout, :mood, :length)
  end

  def find_workout
    @workout = Workout.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workout Log Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Workout Log", root_path %>
      </div>
    </div>
    <div class="nav navbar-nav navbar-right">
      <%= link_to "New Workout", new_workout_path %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </nav>
</body>
</html>

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>

  <%= f.label :date%>
  <%= f.datetime_select :date%><br>

  <%= f.label :workout%>
  <%= f.text_field :workout%><br>

  <%= f.label :mood%>
  <%= f.text_field :mood%><br>

  <%= f.label :length%>
  <%= f.text_field :length%><br>

  <%= f.submit %>
<% end %>

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>

<%= render 'form' %>

<%= link_to "Cancel", root_path %>

app/views/workouts/index.html.erb
<h1>This is the Workouts#Index placeholder</h1>

<% @workouts.each do |workout| %>
  <h2><%= link_to workout.date, workout %></h2>
  <h3><%= workout.workout %></h3>
<%end%>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form' %>

<%= link_to "Cancel", root_path %> 

app/views/workouts/show.html.erb
<div class="workout">
  <p> <%= @workout.date %></p>
  <p> <%= @workout.workout %></p>
  <p> <%= @workout.mood %></p>
  <p> <%= @workout.length %></p>
</div>

<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_workout_path(@workout) %>
<%= link_to "Delete", workout_path(@workout), method: :delete%>